Added comonent Files
morphocluster/morphocluster pull request #103
Opened 2023-08-09 10:11 UTC by TorgeSchwark

created a componend files and changed the nav-bar.

Closes #xxxx

- [ ] Python
  - [ ] tests coverage
  - [ ] tests pass
- [ ] JavaScript
  - [ ] Builds
- [ ] Successful manual test
- [ ] Changelog

2023-09-04 10:30 UTC, moi90 requested changes

2023-09-04 10:30 UTC, moi90 commented on morphocluster/api.py
> +
TODO: Doc

2023-09-04 10:30 UTC, moi90 commented on morphocluster/api.py
> +    directory_path = app.config["FILES_DIR"]
TODO: Actually use `path`

2023-09-04 10:30 UTC, moi90 commented on morphocluster/api.py
> +# path=os.path.relpath(tree_fn, api.config["FILES_DIR"])
Delete

2023-09-04 10:30 UTC, moi90 commented on morphocluster/frontend/src/router.js
> +      path: '/files/:file_path',
TODO: Make `path` optional

https://stackoverflow.com/a/47828416/1116842

2023-09-04 10:30 UTC, moi90 commented on morphocluster/api.py
> +            "Name": entry.name,
TODO: Lowercase fields

2023-09-04 10:30 UTC, moi90 commented on morphocluster/frontend/src/views/Projects.vue
> -import DarkModeControl from "@/components/DarkModeControl.vue";
TODO: Keep DarkModeControl

2023-09-25 13:31 UTC, moi90 requested changes
Good improvements! See my comments.

2023-09-25 13:31 UTC, moi90 commented on morphocluster/api.py
> +        directory_path = app.config["FILES_DIR"]+"/"+path
Use `os.path.join`. This also takes care of an empty `path` so you don't need a `if`-conditional.

2023-09-25 13:31 UTC, moi90 commented on morphocluster/frontend/src/helpers/api.js
> +export function getFile(file_path){
This is not needed as the URL is handled directly by the browser.

2023-09-25 13:31 UTC, moi90 commented on morphocluster/frontend/src/views/Files.vue
> +                        <a class="nav-link active" >Files/{{ this.file_path }}<span class="sr-only">(current)</span></a>
Please split the path components so that the user can navigate to any parent directory.

2023-10-05 09:02 UTC, moi90 requested changes
Thanks for the upload feature!

Please use `werkzeug.secure_filename` where user-provided filenames are used internally, i.e. the `path` parameter of the `/files/` routes or the name of uploaded files.

Please use English throughout and from the start.

2023-10-11 18:29 UTC, moi90 commented on morphocluster/api.py
> +            file_path_on_server = secure_filename(os.path.join(app.config["FILES_DIR"],
Don't use `secure_filename` twice ;)

2023-11-06 19:54 UTC, moi90 commented on morphocluster/api.py
>      """
`path = secure_filename(path)`

2023-11-06 19:54 UTC, moi90 commented on morphocluster/api.py
> +
`path = secure_filename(path)`

2023-11-06 19:56 UTC, moi90 commented on morphocluster/api.py
> +    try:
Remove `try: ... except: raise 500`. Flask does this automatically.

2023-11-06 20:00 UTC, moi90 commented on morphocluster/api.py
> +        if os.path.exists(file_path_on_server) and os.path.isfile(file_path_on_server):
`exists(...) and isfile(...)` is redundant. `isfile` is enough. Also, return early if file not found:

```python
if not os.path.isfile(path):
    raise werkzeug.exceptions.NotFound()

file_info = {...}
return jsonify(file_info)
```

Also, don't create a list, you only return information on one file!

2023-11-06 20:14 UTC, moi90 commented on morphocluster/api.py
> +def get_file(file_path):
Same. `secure_filename`, don't return 500 error, raise `NotFound` early. Finally send file.

2023-11-06 20:17 UTC, moi90 commented on morphocluster/api.py
> +def upload_file(path=""):
`secure_file(path)`. No `try ... return 500`. `if not upload_file: raise werkzeug.exceptions.BadRequest()`.

2023-11-06 21:17 UTC, moi90 commented on morphocluster/frontend/src/views/Files.vue
> +                    window.location.reload();
Don't reload, just call `initialize()` again.

2023-11-06 21:20 UTC, moi90 commented on morphocluster/frontend/src/views/Files.vue
> +            for (let i = 0; i < selectedFiles.length; i++) {
If you have to process multiple files anyway, you should create the FormData object here, add all the files and upload them in one go. (Adjust api.py accordingly.)

2023-11-06 21:21 UTC, moi90 commented on morphocluster/frontend/src/views/Files.vue
> +        async handleDrop(event) {
handleDrop and handleFileUpload are virtually identical. Refactor common functionality into a method that is called by both.

2023-11-14 19:06 UTC, moi90 commented on morphocluster/frontend/src/views/File.vue
> +
Please merge functionality into `Files.vue` (analogously to api.py:get_filesystem_entry).

2023-11-14 19:13 UTC, moi90 commented on morphocluster/frontend/src/views/Project.vue
> +                        <a class="nav-link" href="/p" >Projects</a>
Never use `<a href="..."/>` links in Vue. Use `<router-link class="nav-link" :to=.../>`.

2023-11-14 19:37 UTC, moi90 commented on morphocluster/frontend/src/views/Projects.vue
> +                    </li>
Use `<router-link/>`

2023-11-24 20:09 UTC, moi90 commented on morphocluster/api.py
> +def secure_path_and_name(path: str):
Why do we need two slightly different functions?

2023-11-24 20:13 UTC, moi90 commented on morphocluster/api.py
> +            "breadcrumb_paths": breadcrumb_paths,
Call it "parents". The usage in the breadcrumb is not relevant here.

2023-11-24 20:17 UTC, moi90 commented on morphocluster/frontend/src/views/Projects.vue
> -            <dark-mode-control />
Restore the darkmode control!

2023-11-24 20:25 UTC, moi90 commented on morphocluster/frontend/src/views/Files.vue
> +                window.open(`/api/files/${this.file.path}` + "?download=1");
We shouldn't need to build an url here. Use url_for in api.py to construct complete paths and leave no guesswork for the clients.

2023-11-24 21:20 UTC, TorgeSchwark commented on morphocluster/api.py
> +def secure_path_and_name(path: str):
In case someone added a Directory directly to the Server with not Secure_filename. For example the request for "new Directory" would otherwise search for "new_Directory" which would raise an Error.

2023-11-24 21:45 UTC, moi90 commented on morphocluster/api.py
> +def secure_path_and_name(path: str):
True! Then I think we should use secure_filename only for uploaded files. For existing paths (which may have been created outside of MorphoCluster), we need to allow everything that the underlying filesystem allows. However, we should not navigate to or display hidden or special files.

2023-12-11 08:49 UTC, merged